### ISSUE TITLE
大佬您好，微信通知按照您的教程改了代码，然后编译时候就不能编译了，只有删除功能

### ISSUE THREAD

**Issue by aliporcins** [281677160/AutoBuild-OpenWrt#11]
请问能否把微信通知直接加入代码和您上个版本一样设置里直接开启就行了？

**Comment by 281677160** [comment]
https://github.com/danshui-git/shuoming/blob/master/ms.md
这里就有微信通知的代码，你复制后替换原来的电报代码就可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/AutoBuild-OpenWrt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月21日(星期三) 上午10:42
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[281677160/AutoBuild-OpenWrt] 大佬您好，微信通知按照您的教程改了代码，然后编译时候就不能编译了，只有删除功能 (#11)





 
请问能否把微信通知直接加入代码和您上个版本一样设置里直接开启就行了？

**Comment by aliporcins** [comment]
> https://github.com/danshui-git/shuoming/blob/master/ms.md 这里就有微信通知的代码，你复制后替换原来的电报代码就可以了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" ***@***.***&gt;; 发送时间:&nbsp;2021年7月21日(星期三) 上午10:42 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[281677160/AutoBuild-OpenWrt] 大佬您好，微信通知按照您的教程改了代码，然后编译时候就不能编译了，只有删除功能 (#11) 请问能否把微信通知直接加入代码和您上个版本一样设置里直接开启就行了？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我尝试把代码替换，但是一直没成功，我再试试，要是能像以前的版本直接有个开关就好了

**Comment by 281677160** [comment]
我不知道你要啥开关，电报的跟微信就同一个开关，不要电报的，就把电报代码替换成微信的就可以了，怎么没开关？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月21日(周三) 晚上11:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [281677160/AutoBuild-OpenWrt] 大佬您好，微信通知按照您的教程改了代码，然后编译时候就不能编译了，只有删除功能 (#11)




  
https://github.com/danshui-git/shuoming/blob/master/ms.md 这里就有微信通知的代码，你复制后替换原来的电报代码就可以了
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.&gt;; 发送时间:&nbsp;2021年7月21日(星期三) 上午10:42 @.&gt;; @.***&gt;; 主题:&nbsp;[281677160/AutoBuild-OpenWrt] 大佬您好，微信通知按照您的教程改了代码，然后编译时候就不能编译了，只有删除功能 (#11) 请问能否把微信通知直接加入代码和您上个版本一样设置里直接开启就行了？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
我尝试把代码替换，但是一直没成功，我再试试，要是能像以前的版本直接有个开关就好了

**Comment by aliporcins** [comment]
> 我不知道你要啥开关，电报的跟微信就同一个开关，不要电报的，就把电报代码替换成微信的就可以了，怎么没开关？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年7月21日(周三) 晚上11:26 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [281677160/AutoBuild-OpenWrt] 大佬您好，微信通知按照您的教程改了代码，然后编译时候就不能编译了，只有删除功能 (#11) https://github.com/danshui-git/shuoming/blob/master/ms.md 这里就有微信通知的代码，你复制后替换原来的电报代码就可以了 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.&gt;; 发送时间:&nbsp;2021年7月21日(星期三) 上午10:42 @.&gt;; @.***&gt;; 主题:&nbsp;[281677160/AutoBuild-OpenWrt] 大佬您好，微信通知按照您的教程改了代码，然后编译时候就不能编译了，只有删除功能 (#11) 请问能否把微信通知直接加入代码和您上个版本一样设置里直接开启就行了？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 我尝试把代码替换，但是一直没成功，我再试试，要是能像以前的版本直接有个开关就好了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

大佬，能否把替换代码截图看下？我替换一直不成功

**Comment by 281677160** [comment]
https://github.com/danshui-git/shuoming/blob/master/ms.md 自己去看说明吧，加了图片说明了，想要微信通知，请设置好新版微信通知的密匙，新版微信通知一天只能发送5次消息，想要多发送就只能买会员了

**Comment by aliporcins** [comment]
> https://github.com/danshui-git/shuoming/blob/master/ms.md 自己去看说明吧，加了图片说明了，想要微信通知，请设置好新版微信通知的密匙，新版微信通知一天只能发送5次消息，想要多发送就只能买会员了

好的，谢谢大佬
