### ISSUE TITLE
请教一下大神 你的代码能编译原生openwrt吗？

### ISSUE THREAD

**Issue by Thanf-code** [281677160/AutoBuild-OpenWrt#5]
项目地址 https://github.com/openwrt/openwrt

**Comment by 281677160** [comment]
不想折腾官方的，没必要，BUG太多，如果你不需要其他插件的话，就纯粹的官方代码就随便搞




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/AutoBuild-OpenWrt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月29日(星期二) 中午11:20
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5)





 
项目地址 https://github.com/openwrt/openwrt

**Comment by Thanf-code** [comment]
> 不想折腾官方的，没必要，BUG太多，如果你不需要其他插件的话，就纯粹的官方代码就随便搞
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" ***@***.***&gt;; 发送时间:&nbsp;2021年6月29日(星期二) 中午11:20 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 项目地址 https://github.com/openwrt/openwrt — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.


> 不想折腾官方的，没必要，BUG太多，如果你不需要其他插件的话，就纯粹的官方代码就随便搞
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" ***@***.***&gt;; 发送时间:&nbsp;2021年6月29日(星期二) 中午11:20 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 项目地址 https://github.com/openwrt/openwrt — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

主要是想要官方的主界面   无线下面各个设备后面有个断开连接可以断开设备重连

**Comment by 281677160** [comment]
这个跟界面有啥关系？不是插件功能？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/AutoBuild-OpenWrt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月29日(星期二) 中午11:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5)





  
不想折腾官方的，没必要，BUG太多，如果你不需要其他插件的话，就纯粹的官方代码就随便搞
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.&gt;; 发送时间:&nbsp;2021年6月29日(星期二) 中午11:20 @.&gt;; @.***&gt;; 主题:&nbsp;[281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 项目地址 https://github.com/openwrt/openwrt — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
   
不想折腾官方的，没必要，BUG太多，如果你不需要其他插件的话，就纯粹的官方代码就随便搞
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.&gt;; 发送时间:&nbsp;2021年6月29日(星期二) 中午11:20 @.&gt;; @.***&gt;; 主题:&nbsp;[281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 项目地址 https://github.com/openwrt/openwrt — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
主要是想要官方的主界面   无线下面各个设备后面有个断开连接可以断开设备重连

**Comment by Thanf-code** [comment]
> 这个跟界面有啥关系？不是插件功能？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" ***@***.***&gt;; 发送时间:&nbsp;2021年6月29日(星期二) 中午11:38 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 不想折腾官方的，没必要，BUG太多，如果你不需要其他插件的话，就纯粹的官方代码就随便搞 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.&gt;; 发送时间:&nbsp;2021年6月29日(星期二) 中午11:20 @.&gt;; @.***&gt;; 主题:&nbsp;[281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 项目地址 https://github.com/openwrt/openwrt — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 不想折腾官方的，没必要，BUG太多，如果你不需要其他插件的话，就纯粹的官方代码就随便搞 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.&gt;; 发送时间:&nbsp;2021年6月29日(星期二) 中午11:20 @.&gt;; @.***&gt;; 主题:&nbsp;[281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 项目地址 https://github.com/openwrt/openwrt — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 主要是想要官方的主界面 无线下面各个设备后面有个断开连接可以断开设备重连 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

![Screenshot_20210629_115503](https://user-images.githubusercontent.com/82493550/123737278-3f813c80-d8d5-11eb-91a9-8e464d495b92.jpg)

**Comment by 281677160** [comment]
你这个是官方的19.07?官方的想用ssr plus的话，要替换L大源码的几个文件，还要打一个补丁，然后也有一堆BUG，L大最近同步官方最新内核版本都折腾了半个月还没修复完全部BUG，不过如果你只用官方插件加一个ssr plus问题应该不大




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/AutoBuild-OpenWrt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月29日(星期二) 中午12:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5)





  
这个跟界面有啥关系？不是插件功能？
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.&gt;; 发送时间:&nbsp;2021年6月29日(星期二) 中午11:38 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 不想折腾官方的，没必要，BUG太多，如果你不需要其他插件的话，就纯粹的官方代码就随便搞 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.&gt;; 发送时间:&nbsp;2021年6月29日(星期二) 中午11:20 @.&gt;; @.&gt;; 主题:&nbsp;[281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 项目地址 https://github.com/openwrt/openwrt — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 不想折腾官方的，没必要，BUG太多，如果你不需要其他插件的话，就纯粹的官方代码就随便搞 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.&gt;; 发送时间:&nbsp;2021年6月29日(星期二) 中午11:20 @.&gt;; @.&gt;; 主题:&nbsp;[281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 项目地址 https://github.com/openwrt/openwrt — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 主要是想要官方的主界面 无线下面各个设备后面有个断开连接可以断开设备重连 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Thanf-code** [comment]
> 你这个是官方的19.07?官方的想用ssr plus的话，要替换L大源码的几个文件，还要打一个补丁，然后也有一堆BUG，L大最近同步官方最新内核版本都折腾了半个月还没修复完全部BUG，不过如果你只用官方插件加一个ssr plus问题应该不大
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" ***@***.***&gt;; 发送时间:&nbsp;2021年6月29日(星期二) 中午12:27 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 这个跟界面有啥关系？不是插件功能？ … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.&gt;; 发送时间:&nbsp;2021年6月29日(星期二) 中午11:38 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 不想折腾官方的，没必要，BUG太多，如果你不需要其他插件的话，就纯粹的官方代码就随便搞 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.&gt;; 发送时间:&nbsp;2021年6月29日(星期二) 中午11:20 @.&gt;; @.&gt;; 主题:&nbsp;[281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 项目地址 https://github.com/openwrt/openwrt — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 不想折腾官方的，没必要，BUG太多，如果你不需要其他插件的话，就纯粹的官方代码就随便搞 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.&gt;; 发送时间:&nbsp;2021年6月29日(星期二) 中午11:20 @.&gt;; @.&gt;; 主题:&nbsp;[281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 项目地址 https://github.com/openwrt/openwrt — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 主要是想要官方的主界面 无线下面各个设备后面有个断开连接可以断开设备重连 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

更换luci？？

**Comment by Thanf-code** [comment]
> 你这个是官方的19.07?官方的想用ssr plus的话，要替换L大源码的几个文件，还要打一个补丁，然后也有一堆BUG，L大最近同步官方最新内核版本都折腾了半个月还没修复完全部BUG，不过如果你只用官方插件加一个ssr plus问题应该不大
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" ***@***.***&gt;; 发送时间:&nbsp;2021年6月29日(星期二) 中午12:27 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 这个跟界面有啥关系？不是插件功能？ … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.&gt;; 发送时间:&nbsp;2021年6月29日(星期二) 中午11:38 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 不想折腾官方的，没必要，BUG太多，如果你不需要其他插件的话，就纯粹的官方代码就随便搞 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.&gt;; 发送时间:&nbsp;2021年6月29日(星期二) 中午11:20 @.&gt;; @.&gt;; 主题:&nbsp;[281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 项目地址 https://github.com/openwrt/openwrt — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 不想折腾官方的，没必要，BUG太多，如果你不需要其他插件的话，就纯粹的官方代码就随便搞 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.&gt;; 发送时间:&nbsp;2021年6月29日(星期二) 中午11:20 @.&gt;; @.&gt;; 主题:&nbsp;[281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 项目地址 https://github.com/openwrt/openwrt — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 主要是想要官方的主界面 无线下面各个设备后面有个断开连接可以断开设备重连 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

要实现上图界面  要更换luci吗？

**Comment by 281677160** [comment]
> > 你这个是官方的19.07?官方的想用ssr plus的话，要替换L大源码的几个文件，还要打一个补丁，然后也有一堆BUG，L大最近同步官方最新内核版本都折腾了半个月还没修复完全部BUG，不过如果你只用官方插件加一个ssr plus问题应该不大
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "281677160/AutoBuild-OpenWrt" _**@**_._**>; 发送时间: 2021年6月29日(星期二) 中午12:27 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 这个跟界面有啥关系？不是插件功能？ … ------------------ 原始邮件 ------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.>; 发送时间: 2021年6月29日(星期二) 中午11:38 @.>; @.@.>; 主题: Re: [281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 不想折腾官方的，没必要，BUG太多，如果你不需要其他插件的话，就纯粹的官方代码就随便搞 … ------------------ 原始邮件 ------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.>; 发送时间: 2021年6月29日(星期二) 中午11:20 @.>; @.>; 主题: [281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 项目地址 https://github.com/openwrt/openwrt — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 不想折腾官方的，没必要，BUG太多，如果你不需要其他插件的话，就纯粹的官方代码就随便搞 … ------------------ 原始邮件 ------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.>; 发送时间: 2021年6月29日(星期二) 中午11:20 @.>; @.>; 主题: [281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 项目地址 https://github.com/openwrt/openwrt — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 主要是想要官方的主界面 无线下面各个设备后面有个断开连接可以断开设备重连 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 要实现上图界面 要更换luci吗？

用你的配置文件来编译了一个21.02的，不知道什么情况，你下载来测试下看看把，下面是固件地址
https://github.com/281677160/AutoBuild-OpenWrt/suites/3113653954/artifacts/71339777

**Comment by Thanf-code** [comment]
> > > 你这个是官方的19.07?官方的想用ssr plus的话，要替换L大源码的几个文件，还要打一个补丁，然后也有一堆BUG，L大最近同步官方最新内核版本都折腾了半个月还没修复完全部BUG，不过如果你只用官方插件加一个ssr plus问题应该不大
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: "281677160/AutoBuild-OpenWrt" _**@**_._**>; 发送时间: 2021年6月29日(星期二) 中午12:27 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 这个跟界面有啥关系？不是插件功能？ … ------------------ 原始邮件 ------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.>; 发送时间: 2021年6月29日(星期二) 中午11:38 @.>; @.@.>; 主题: Re: [281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 不想折腾官方的，没必要，BUG太多，如果你不需要其他插件的话，就纯粹的官方代码就随便搞 … ------------------ 原始邮件 ------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.>; 发送时间: 2021年6月29日(星期二) 中午11:20 @.>; @.>; 主题: [281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 项目地址 https://github.com/openwrt/openwrt — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 不想折腾官方的，没必要，BUG太多，如果你不需要其他插件的话，就纯粹的官方代码就随便搞 … ------------------ 原始邮件 ------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.>; 发送时间: 2021年6月29日(星期二) 中午11:20 @.>; @.>; 主题: [281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 项目地址 https://github.com/openwrt/openwrt — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 主要是想要官方的主界面 无线下面各个设备后面有个断开连接可以断开设备重连 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > 要实现上图界面 要更换luci吗？
> 
> 用你的配置文件来编译了一个21.02的，不知道什么情况，你下载来测试下看看把，下面是固件地址
> https://github.com/281677160/AutoBuild-OpenWrt/suites/3113653954/artifacts/71339777

这个固件太大了  我的新路由3 闪存32M 内存512M  重新更新了配置  
请教下大神怎么编译21.02

**Comment by 281677160** [comment]
呃，那是21.02原因吧，我都是复制你仓库的配置编译的，要不然就是你仓库配置有问题


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/AutoBuild-OpenWrt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月30日(星期三) 上午8:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5)





    
你这个是官方的19.07?官方的想用ssr plus的话，要替换L大源码的几个文件，还要打一个补丁，然后也有一堆BUG，L大最近同步官方最新内核版本都折腾了半个月还没修复完全部BUG，不过如果你只用官方插件加一个ssr plus问题应该不大
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.&gt;; 发送时间:&nbsp;2021年6月29日(星期二) 中午12:27 _@**._&gt;; ***@***.***@.**_&gt;; 主题:&nbsp;Re: [281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 这个跟界面有啥关系？不是插件功能？ … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.&gt;; 发送时间:&nbsp;2021年6月29日(星期二) 中午11:38 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 不想折腾官方的，没必要，BUG太多，如果你不需要其他插件的话，就纯粹的官方代码就随便搞 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.&gt;; 发送时间:&nbsp;2021年6月29日(星期二) 中午11:20 @.&gt;; @.&gt;; 主题:&nbsp;[281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 项目地址 https://github.com/openwrt/openwrt — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 不想折腾官方的，没必要，BUG太多，如果你不需要其他插件的话，就纯粹的官方代码就随便搞 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.&gt;; 发送时间:&nbsp;2021年6月29日(星期二) 中午11:20 @.&gt;; @.&gt;; 主题:&nbsp;[281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 项目地址 https://github.com/openwrt/openwrt — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 主要是想要官方的主界面 无线下面各个设备后面有个断开连接可以断开设备重连 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
要实现上图界面 要更换luci吗？
  
用你的配置文件来编译了一个21.02的，不知道什么情况，你下载来测试下看看把，下面是固件地址
 https://github.com/281677160/AutoBuild-OpenWrt/suites/3113653954/artifacts/71339777
  
这个固件太大了  我的新路由3 闪存32M 内存512M  重新更新了配置
 请教下大神怎么编译21.02

**Comment by Thanf-code** [comment]
> 呃，那是21.02原因吧，我都是复制你仓库的配置编译的，要不然就是你仓库配置有问题
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" ***@***.***&gt;; 发送时间:&nbsp;2021年6月30日(星期三) 上午8:53 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 你这个是官方的19.07?官方的想用ssr plus的话，要替换L大源码的几个文件，还要打一个补丁，然后也有一堆BUG，L大最近同步官方最新内核版本都折腾了半个月还没修复完全部BUG，不过如果你只用官方插件加一个ssr plus问题应该不大 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.&gt;; 发送时间:&nbsp;2021年6月29日(星期二) 中午12:27 _@**._&gt;; ***@***.***@.**_&gt;; 主题:&nbsp;Re: [281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 这个跟界面有啥关系？不是插件功能？ … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.&gt;; 发送时间:&nbsp;2021年6月29日(星期二) 中午11:38 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 不想折腾官方的，没必要，BUG太多，如果你不需要其他插件的话，就纯粹的官方代码就随便搞 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.&gt;; 发送时间:&nbsp;2021年6月29日(星期二) 中午11:20 @.&gt;; @.&gt;; 主题:&nbsp;[281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 项目地址 https://github.com/openwrt/openwrt — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 不想折腾官方的，没必要，BUG太多，如果你不需要其他插件的话，就纯粹的官方代码就随便搞 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.&gt;; 发送时间:&nbsp;2021年6月29日(星期二) 中午11:20 @.&gt;; @.&gt;; 主题:&nbsp;[281677160/AutoBuild-OpenWrt] 请教一下大神 你的代码能编译原生openwrt吗？ (#5) 项目地址 https://github.com/openwrt/openwrt — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 主要是想要官方的主界面 无线下面各个设备后面有个断开连接可以断开设备重连 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 要实现上图界面 要更换luci吗？ 用你的配置文件来编译了一个21.02的，不知道什么情况，你下载来测试下看看把，下面是固件地址 https://github.com/281677160/AutoBuild-OpenWrt/suites/3113653954/artifacts/71339777 这个固件太大了 我的新路由3 闪存32M 内存512M 重新更新了配置 请教下大神怎么编译21.02 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

是我配置的问题  我更新了
