### ISSUE TITLE
大佬您好，请问能添加docker和定时唤醒这2个插件吗？

### ISSUE THREAD

**Issue by aliporcins** [281677160/AutoBuild-OpenWrt#8]
大佬您好，请问能添加docker和定时唤醒这2个插件吗？

**Comment by 281677160** [comment]
定时唤醒定时唤醒叫什么名字？我记得所有源码都带的，docker所有源码都自带，如果没有就看我插件包有说明怎么才会显示




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/AutoBuild-OpenWrt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月4日(星期天) 中午11:35
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[281677160/AutoBuild-OpenWrt] 大佬您好，请问能添加docker和定时唤醒这2个插件吗？ (#8)





 
大佬您好，请问能添加docker和定时唤醒这2个插件吗？

**Comment by aliporcins** [comment]
> 定时唤醒定时唤醒叫什么名字？我记得所有源码都带的，docker所有源码都自带，如果没有就看我插件包有说明怎么才会显示
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" ***@***.***&gt;; 发送时间:&nbsp;2021年7月4日(星期天) 中午11:35 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[281677160/AutoBuild-OpenWrt] 大佬您好，请问能添加docker和定时唤醒这2个插件吗？ (#8) 大佬您好，请问能添加docker和定时唤醒这2个插件吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

大佬您好，定时唤醒的名字是 luci-app-control-timewol

**Comment by 281677160** [comment]
呃，我仓库有的啊，你编译什么源码没有？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月17日(周六) 晚上10:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [281677160/AutoBuild-OpenWrt] 大佬您好，请问能添加docker和定时唤醒这2个插件吗？ (#8)




  
定时唤醒定时唤醒叫什么名字？我记得所有源码都带的，docker所有源码都自带，如果没有就看我插件包有说明怎么才会显示
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.&gt;; 发送时间:&nbsp;2021年7月4日(星期天) 中午11:35 @.&gt;; @.***&gt;; 主题:&nbsp;[281677160/AutoBuild-OpenWrt] 大佬您好，请问能添加docker和定时唤醒这2个插件吗？ (#8) 大佬您好，请问能添加docker和定时唤醒这2个插件吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
大佬您好，定时唤醒的名字是 luci-app-control-timewol

**Comment by aliporcins** [comment]
> 呃，我仓库有的啊，你编译什么源码没有？
> […](#)
> ---原始邮件--- 发件人: ***@***.***> 发送时间: 2021年7月17日(周六) 晚上10:45 收件人: ***@***.***>; 抄送: ***@***.******@***.***>; 主题: Re: [281677160/AutoBuild-OpenWrt] 大佬您好，请问能添加docker和定时唤醒这2个插件吗？ (#8) 定时唤醒定时唤醒叫什么名字？我记得所有源码都带的，docker所有源码都自带，如果没有就看我插件包有说明怎么才会显示 … ------------------ 原始邮件 ------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.>; 发送时间: 2021年7月4日(星期天) 中午11:35 @.>; @.***>; 主题: [281677160/AutoBuild-OpenWrt] 大佬您好，请问能添加docker和定时唤醒这2个插件吗？ (#8) 大佬您好，请问能添加docker和定时唤醒这2个插件吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 大佬您好，定时唤醒的名字是 luci-app-control-timewol — You are receiving this because you commented. Reply to this email directly,在 GitHub 上查看，或取消订阅。

LEDE,那我现在重新编译再找找，是定时唤醒，不是远程唤醒

**Comment by aliporcins** [comment]
> 呃，我仓库有的啊，你编译什么源码没有？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年7月17日(周六) 晚上10:45 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [281677160/AutoBuild-OpenWrt] 大佬您好，请问能添加docker和定时唤醒这2个插件吗？ (#8) 定时唤醒定时唤醒叫什么名字？我记得所有源码都带的，docker所有源码都自带，如果没有就看我插件包有说明怎么才会显示 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.&gt;; 发送时间:&nbsp;2021年7月4日(星期天) 中午11:35 @.&gt;; @.***&gt;; 主题:&nbsp;[281677160/AutoBuild-OpenWrt] 大佬您好，请问能添加docker和定时唤醒这2个插件吗？ (#8) 大佬您好，请问能添加docker和定时唤醒这2个插件吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 大佬您好，定时唤醒的名字是 luci-app-control-timewol — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

大佬，LEDE的APP里还是没发现有这个timewol插件

**Comment by 281677160** [comment]
那就是你的机型不支持吧，这玩意我记得是有的，我进去看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月17日(周六) 晚上11:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [281677160/AutoBuild-OpenWrt] 大佬您好，请问能添加docker和定时唤醒这2个插件吗？ (#8)




  
呃，我仓库有的啊，你编译什么源码没有？
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年7月17日(周六) 晚上10:45 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [281677160/AutoBuild-OpenWrt] 大佬您好，请问能添加docker和定时唤醒这2个插件吗？ (#8) 定时唤醒定时唤醒叫什么名字？我记得所有源码都带的，docker所有源码都自带，如果没有就看我插件包有说明怎么才会显示 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.&gt;; 发送时间:&nbsp;2021年7月4日(星期天) 中午11:35 @.&gt;; @.***&gt;; 主题:&nbsp;[281677160/AutoBuild-OpenWrt] 大佬您好，请问能添加docker和定时唤醒这2个插件吗？ (#8) 大佬您好，请问能添加docker和定时唤醒这2个插件吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 大佬您好，定时唤醒的名字是 luci-app-control-timewol — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
大佬，LEDE的APP里还是没发现有这个timewol插件

**Comment by aliporcins** [comment]
> 那就是你的机型不支持吧，这玩意我记得是有的，我进去看看
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年7月17日(周六) 晚上11:11 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [281677160/AutoBuild-OpenWrt] 大佬您好，请问能添加docker和定时唤醒这2个插件吗？ (#8) 呃，我仓库有的啊，你编译什么源码没有？ … ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年7月17日(周六) 晚上10:45 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [281677160/AutoBuild-OpenWrt] 大佬您好，请问能添加docker和定时唤醒这2个插件吗？ (#8) 定时唤醒定时唤醒叫什么名字？我记得所有源码都带的，docker所有源码都自带，如果没有就看我插件包有说明怎么才会显示 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/AutoBuild-OpenWrt" @.&gt;; 发送时间:&nbsp;2021年7月4日(星期天) 中午11:35 @.&gt;; @.***&gt;; 主题:&nbsp;[281677160/AutoBuild-OpenWrt] 大佬您好，请问能添加docker和定时唤醒这2个插件吗？ (#8) 大佬您好，请问能添加docker和定时唤醒这2个插件吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 大佬您好，定时唤醒的名字是 luci-app-control-timewol — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 大佬，LEDE的APP里还是没发现有这个timewol插件 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

大佬您看看，我是云编译的，docker我找到了不在APP文件夹，但是一直没找到timewol这个

**Comment by 281677160** [comment]
![QQ截图20210717232510](https://user-images.githubusercontent.com/66651997/126041769-b7c5f170-4c72-490b-aa52-0c2b6bd8e83d.png)

**Comment by 281677160** [comment]
我不知道你编译什么机型找不到，个别机型不支持某插件的情况是有的

**Comment by aliporcins** [comment]
> 我不知道你编译什么机型找不到，个别机型不支持某插件的情况是有的

感谢大佬，我再试试

**Comment by 281677160** [comment]
![QQ截图20210717232814](https://user-images.githubusercontent.com/66651997/126041842-d123f1af-6e83-4536-88ef-5ea68be7bebf.png)

**Comment by 281677160** [comment]
我最早叫你去看我插件包说明的，我不知道你看了没有

**Comment by aliporcins** [comment]
> 我最早叫你去看我插件包说明的，我不知道你看了没有

大佬，请问您编译的也是LEDE吗？

**Comment by 281677160** [comment]
![QQ截图20210717233217](https://user-images.githubusercontent.com/66651997/126042023-ea224f4d-6f4b-42ed-b536-2de3c7943f17.png)
![QQ截图20210717233256](https://user-images.githubusercontent.com/66651997/126042026-c0c8fa7a-624f-40f2-b02d-69f1462d93f8.png)

**Comment by aliporcins** [comment]
感谢大佬，找到了，谢谢！！！

**Comment by aliporcins** [comment]
谢谢大佬！
